apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 10
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: dannydarko/measurement-go
          command: ["./grpc-producer"]
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1024Mi
