apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  type: ClusterIP
  selector:
    app: consumer
  ports:
    - port: 50051
      targetPort: 50051
  sessionAffinity: None
